{{- range $index, $container := tuple .Values.sonarr .Values.radarr .Values.jackett }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sonarr.fullname" $ }}-{{$container.name}}
  labels:
{{ include "sonarr.labels" $ | indent 4  }}
spec:
  type: {{ $container.type }}
  ports:
    - port: 80
      targetPort: {{ $container.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "sonarr.name" $ }}
    release: {{ $.Release.Name }}
{{- end }}
