userId: 1000
replicaCount: 1
timezone: America/Chicago

internalPort: 8989
name: sonarr
image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: Always
volumeMounts:
  - mountPath: "/config"
    name: "sonarr-config"
  - mountPath: "/tv"
    name: "television-library"
  - mountPath: "/downloads"
    name: "torrent-downloads"
resources:
  requests:
    cpu: .5 
    memory: 2Gi
  limits:
    memory: 2Gi
volumes:
  - name: dev-net-tun
    hostPath:
      path: /dev/net/tun
# TODO: You will need to configure these host paths before the chart will work
  - name: sonarr-config
    hostPath:
      path: "/data"
  - name: television-library
    hostPath:
      path: "/data"
  - name: torrent-downloads
    hostPath:
      path: "/data"
