apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unifi-exporter.fullname" . }}
  labels:
    {{- include "unifi-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yml: |
{{ toYaml .Values.config | indent 4 }}
