apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "unifi-exporter.fullname" . }}
  labels:
    {{- include "unifi-exporter.labels" . | nindent 4 }}
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      {{- include "unifi-exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - interval: 60s
    port: metrics
    path: "/metrics"
