repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
releases:
  - name: docker-gc
    chart: stable/spotify-docker-gc
    version: 0.3.0
  - name: nginx-ingress
    chart: stable/nginx-ingress
    version: ~1.1.4
    values:
      - controller:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          nodeSelector:
            kubernetes.io/hostname: nimbus
          minAvailable: 0
        defaultBackend:
          minAvailable: 0
        rbac:
          create: true
  - name: home-assistant
    chart: stable/home-assistant
    version: ~0.5.1
    values:
      - image:
          tag: 0.86.2
      - values/home-assistant_values.yaml
  - name: media-master
    chart: ./media-master
    version: ~0.3.1
    values:
      - values/media-master_values.yaml
  - name: ftb-infinity
    chart: stable/minecraft
    version: ~0.3.2
    values:
      - securityContext:
          # Security context settings
          runAsUser: 0
        minecraftServer:
          eula: "TRUE"
          type: "FTB"
          version: "1.12.2"
          ftbServerMod: https://www.feed-the-beast.com/projects/ftb-revelation/files/2658240
          jvmOpts: "-Xmx4G -Xms4G"
        resources:
          requests:
            memory: 4Gi
            cpu: 1
          limits:
            memory: 4Gi
            cpu: 1
        persistence:
          storageClass: cephfs
          dataDir:
            enabled: true
            Size: 20Gi
  - name: prometheus
    chart: stable/prometheus-operator
    version: ~0.1.31
    values:
      - alertmanager:
          requests:
            memory: 400Mi
          limits:
            memory: 400Mi
        prometheusOperator:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        prometheus:
          prometheusSpec:
            additionalScrapeConfigs:
            - job_name: 'ceph'
              honor_labels: true
              static_configs:
              - targets:  
                - "10.0.0.1:9283"
                - "10.0.0.3:9283"
                labels: {}
          requests:
            memory: 400Mi
          limits:
            memory: 400Mi
  - name: metallb
    chart: stable/metallb
    version: ~0.8.0
    values:
    - configInline:
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 192.168.1.220-192.168.1.240
      controller:
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
      speaker:
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        affinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/hostname"
                  operator: In
                  values: ["absis", "leviathan"]
