repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: kiwigrid
    url: https://kiwigrid.github.io
  - name: pingcap
    url: http://charts.pingcap.org
  - name: jetstack
    url: https://charts.jetstack.io
  - name: loki
    url: https://grafana.github.io/loki/charts
  - name: itzg
    url: https://itzg.github.io/minecraft-server-charts/
  - name: billimek
    url: https://billimek.com/billimek-charts
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    version: ~0.12.0
    namespace: cert-manager
  - name: goldpinger
    chart: stable/goldpinger
    version: ~2.0.1
    values:
      - resources:
          limits:
            memory: 50Mi
          requests:
            memory: 50Mi
        serviceMonitor:
          enabled: true
          namespace: default
  - name: docker-gc
    chart: stable/spotify-docker-gc
    version: 0.3.0
    values:
      - resources:
          requests:
            memory: 10Mi
          limits:
            memory: 10Mi
  - name: nginx-ingress
    chart: stable/nginx-ingress
    version: ~1.1.4
    values:
      - controller:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          nodeSelector:
            kubernetes.io/hostname: nimbus
          minAvailable: 0
          resources:
           limits:
             memory: 400Mi
           requests:
             cpu: 100m
             memory: 400Mi
        defaultBackend:
          minAvailable: 0
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
          service:
            omitClusterIP: true
        rbac:
          create: true
  - name: home-assistant
    chart: billimek/home-assistant
    version: ~1.0.5
    values:
      - persistence:
          enabled: true
          size: 32Gi
          accessMode: ReadWriteMany
          storageClass: "cephfs"
        probes:
          liveness:
            enabled: false
        nodeSelector:
          kubernetes.io/hostname: leviathan
        monitoring:
          enabled: true
        resources:
          limits:
           memory: 2Gi
          requests:
           cpu: 500m
           memory: 2Gi
      - values/home-assistant_values.yaml
  - name: transmission-ovpn
    chart: ./transmission-ovpn
    version: ~0.1.0
    values:
      - values/transmission-ovpn.yaml
  - name: radarr
    chart: ./radarr
    version: ~0.1.0
    values:
      - values/radarr.yaml
  - name: sonarr
    chart: ./sonarr
    version: ~0.1.0
    values:
      - values/sonarr.yaml
  - name: jackett
    chart: ./jackett
    version: ~0.1.0
    values:
      - values/jackett.yaml
  - name: ftb-infinity
    chart: stable/minecraft
    version: ~0.3.2
    values:
      - securityContext:
          # Security context settings
          # ceph's volume provisioner needs to be run as root right now
          runAsUser: 0
        minecraftServer:
          eula: "TRUE"
          type: "FTB"
          version: "1.12.2"
          ftbServerMod: https://www.feed-the-beast.com/projects/ftb-revelation/files/2658240
          jvmOpts: "-Xmx6G -Xms6G"
          serviceType: "NodePort"
        resources:
          requests:
            memory: 6Gi
            cpu: 1
          limits:
            memory: 6Gi
            cpu: 1
        persistence:
          storageClass: cephfs
          dataDir:
            enabled: true
            Size: 20Gi
  - name: wobbling-crab
    chart: ./ombi
    version: ~0.1.0
    values:
      - values/ombi_values.yaml

  - name: solemn-echidna
    chart: ./plex
    version: ~0.3.1
    values:
      - values/plex_values.yaml
  - name: prometheus
    chart: stable/prometheus-operator
    version: ~8.15.6
    values:
      - alertmanager:
          resources:
            requests:
              memory: 400Mi
            limits:
              memory: 400Mi
        prometheusOperator:
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
        prometheus:
          prometheusSpec:
            securityContext:
              runAsNonRoot: false
              runAsUser: 0
              fsGroup: 0
            retention: 12w
            storageSpec:
              volumeClaimTemplate:
               spec:
                 storageClassName: cephfs
                 accessModes: ["ReadWriteMany"]
                 resources:
                   requests:
                     storage: 100Gi
            additionalScrapeConfigs:
            - job_name: 'ceph'
              honor_labels: true
              static_configs:
              - targets:
                - "10.0.0.1:9283"
                - "10.0.0.3:9283"
                - "10.0.0.6:9283"
                labels: { "cluster": "stapler1" }
            resources:
              requests:
                memory: 5Gi
              limits:
                memory: 5Gi
        prometheus-node-exporter:
          resources:
            limits:
              cpu: 200m
              memory: 50Mi
            requests:
              cpu: 100m
              memory: 30Mi
        grafana:
          enabled: true
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - graph.staplerstation.com
            tls:
            - hosts:
               - graph.staplerstation.com
              secretName: grafana-ingress
          grafana.ini:
            server:
              domain: graph.staplerstation.com
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
          persistence:
            enabled: true
            size: 32Gi
            accessMode: ReadWriteMany
            storageClassName: "cephfs"
  - name: loki
    chart: loki/loki-stack
    version: 0.38.1
    values:
      - resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
  - name: tidb-operator
    chart: pingcap/tidb-operator
    version: 1.1.3
    namespace: pingcap
  - name: tidb-cluster
    chart: pingcap/tidb-cluster
    version: 1.1.3
    namespace: pingcap
    values:
    - tidb:
        passwordSecretName: tidb-secret
        config: |
          [log]
          level = "info"
        initSql: |-
          CREATE DATABASE zoneminder;
          GRANT ALL PRIVILEGES ON zoneminder.* TO 'developer'@'%';
      pd:
        storageClassName: cephfs
        resources:
          storage: 20Gi
      monitor:
        storageClassName: cephfs
      tikv:
        storageClassName: cephfs
  - name: metallb
    chart: stable/metallb
    version: ~0.12.0
    values:
    - configInline:
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 192.168.1.220-192.168.1.240
      controller:
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
      speaker:
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values: ["absis", "leviathan"]
