apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "transmission-ovpn.fullname" . }}
  labels:
{{ include "transmission-ovpn.labels" . | indent 4 }}
spec:
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "transmission-ovpn.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.internalPort }}
          {{ if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          {{ end }}
          {{ if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.net_admin}}
          # Add net_admin for VPN to use TUN
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
          {{- end }}
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}
          env:
          {{- if $.Values.timezone }}
          - name: TZ
            value: {{ $.Values.timezone }}
          {{- end}}
          {{- if $.Values.userId }}
          - name: PGID
            value: {{ $.Values.userId | quote }}
          - name: PUID
            value: {{ $.Values.userId | quote }}
          {{- end }}
          {{- if .Values.env}}
            {{- range $key, $value := .Values.env}}
          - name: "{{$key}}"
            value: "{{ $value }}"
            {{- end}}
          {{- end}}
{{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
