---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "transmission-ovpn.fullname" $ }}
  labels:
{{ include "transmission-ovpn.labels" $ | indent 4  }}
spec:
  type: {{ .Values.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "transmission-ovpn.name" $ }}
    release: {{ $.Release.Name }}
