kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "starbound.fullname" . }}
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    {{- toYaml .Values.storage.resources |  nindent 4 }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
