apiVersion: v1
kind: Secret
metadata:
  name: {{ include "starbound.fullname" . }}-steam-creds
type: Opaque
data:
  STEAM_USERNAME: "{{ .Values.steam.username | b64enc }}"
  STEAM_PASSWORD: "{{ .Values.steam.password | b64enc }}"
