---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "radarr.fullname" $ }}
  labels:
{{ include "radarr.labels" $ | indent 4  }}
spec:
  type: {{ .Values.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "radarr.name" $ }}
    release: {{ $.Release.Name }}
