# Default values for transmission-ovpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
userId: 1000
replicaCount: 1
timezone: America/Chicago

name: transmission-ovpn
internalPort: 9091
# Transmision needs net_admin to use the tun interface
net_admin: true
image:
  repository: haugene/transmission-openvpn
  tag: "4.3"
  pullPolicy: Always
readinessProbe:
  exec:
    command:
      - /etc/scripts/healthcheck.sh
  initialDelaySeconds: 120
  periodSeconds: 120
  timeoutSeconds: 30
startupProbe:
  exec:
    command:
      - /etc/scripts/healthcheck.sh
  initialDelaySeconds: 20
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 30

env:
  OPENVPN_PROVIDER: PIA
  OPENVPN_CONFIG: Netherlands
  OPENVPN_USERNAME: p0000000 # Enter your username
  OPENVPN_PASSWORD: password # Enter your password
  PIA_OPENVPN_CONFIG_BUNDLE: openvpn
  LOCAL_NETWORK: 10.233.0.0/18
  CREATE_TUN_DEVICE: true
  DOCKER_LOG: true
  TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED: true
  TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME: /scripts/unrar.sh
volumeMounts:
  - mountPath: "/data"
    name: "torrent-downloads"

# Resources for ~200 Torrents
# resources:
#   requests:
#     cpu: .25
#     memory: 3Gi
#   limits:
#     memory: 3Gi
