# Default values for transmission-ovpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
userId: 1000
replicaCount: 1
timezone: America/Chicago

name: transmission-ovpn
internalPort: 9091
# Transmision needs net_admin to use the tun interface
net_admin: true
image:
  repository: haugene/transmission-openvpn
  tag: "2.12"
  pullPolicy: Always
readinessProbe:
  tcpSocket:
    port: 9091
  initialDelaySeconds: 120
  periodSeconds: 120
env:
  OPENVPN_PROVIDER: PIA
  OPENVPN_CONFIG: Netherlands
  OPENVPN_USERNAME: p0000000 # Enter your username
  OPENVPN_PASSWORD: password # Enter your password
  LOCAL_NETWORK: 10.233.0.0/18
  CREATE_TUN_DEVICE: true
  DOCKER_LOG: true
volumeMounts:
  - mountPath: "/data"
    name: "torrent-downloads"

# Resources for ~200 Torrents
# resources:
#   requests:
#     cpu: .25
#     memory: 3Gi
#   limits:
#     memory: 3Gi
