# Default values for radarr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
userId: 1000
replicaCount: 1
timezone: America/Chicago

name: radarr
internalPort: 7878
readinessProbe:
  httpGet:
    path: /
    port: 7878
  failureThreshold: 3
  periodSeconds: 10
image:
  repository: linuxserver/radarr
  tag: latest
  pullPolicy: Always
volumeMounts:
  - mountPath: "/config"
    name: "radarr-config"
  - mountPath: "/movies"
    name: "movie-library"
  - mountPath: "/downloads"
    name: "torrent-downloads"
resources:
  requests:
    cpu: .5 
    memory: 2Gi
  limits:
    memory: 2Gi

volumes:
  - name: radarr-config
    hostPath:
      path: "/data"
  - name: movie-library
    hostPath:
      path: "/data"
