---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "plex.fullname" . }}
{{- if .Values.ingress.annotations }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  rules:
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "plex.fullname" $ }}
          servicePort: 32400
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
