apiVersion: v1
kind: Service
metadata:
  name: {{ include "athens.fullname" . }}-fluree-ledger
  labels:
    {{- include "athens.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app.kubernetes.io/component: fluree
    {{- include "athens.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "athens.fullname" . }}-fluree-ledger
  labels:
    app.kubernetes.io/component: fluree
    {{- include "athens.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: fluree
      {{- include "athens.labels" . | nindent 6 }}
  serviceName: {{ include "athens.fullname" . }}-fluree-ledger
  replicas: 1 # by default is 1
  # minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: fluree
        {{- include "athens.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: fluree
          image: {{ .Values.fluree.image }}
          ports:
            - containerPort: 8090
              name: web
          volumeMounts:
            - name: fluree-data
              mountPath: /var/lib/fluree
          readinessProbe:
            httpGet:
              port: web
              path: /fdb/health
            periodSeconds: 15
            timeoutSeconds: 40
            failureThreshold: 3
            initialDelaySeconds: 15
          resources:
            requests:
              memory: 2Gi
            limits:
              memory: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: fluree-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storageClass }}
        resources:
          requests:
            storage: {{ .Values.fluree.pvc.requests.storage }}
