# Default values for jackett.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
userId: 1000
replicaCount: 1
timezone: America/Chicago

name: jackett
internalPort: 9117
image:
  repository: linuxserver/jackett
  tag: latest
  pullPolicy: Always
volumeMounts:
  - mountPath: "/config"
    name: "jackett-config"
  - mountPath: "/downloads"
    name: "torrent-downloads"
resources:
  requests:
    memory: "1Gi"
    cpu: .5
  limits:
    memory: "1Gi"

volumes:
  - name: jackett-config
    hostPath:
      path: "/data"
