apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dominions5.fullname" . }}
  labels:
    app: {{ template "dominions5.name" . }}
    chart: {{ template "dominions5.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  DISCORD_BOT_TOKEN: {{ required "A valid .Values.discordSidecar.token is required" .Values.discordSidecar.token }}
